### ISSUE TITLE
执行go run main.go 出现问题

### ISSUE THREAD

**Issue by wuqinqiang** [yehux/Coot#3]
<img width="551" alt="屏幕快照 2019-08-08 下午12 45 01" src="https://user-images.githubusercontent.com/36129334/62675659-734dd300-b9da-11e9-8e73-a43811ac5e76.png">

可是我已经安装了 github.com/domgoer/gotask

**Comment by 1ikeme** [comment]
@wuqinqiang 可能是你安装的方式不对，你应该使用glide安装

**Comment by sanjinhub** [comment]
@wuqinqiang glide 安装即可
